### ISSUE TITLE
Нельзя создать больше одного процесса

### ISSUE THREAD

**Issue by Lemiort** [Alleshka/Gidra#3]
Кнопка активна в непонятные моменты времени. Иногда вся прога крашается

**Comment by Alleshka** [comment]
Нужно воспроизвести. При версии cc24378 всё ок. Когда открыт проект, окно активно.

**Comment by Lemiort** [comment]
На версии  b3652519f7aa1a96c378117f5c346bf4e3bb46f5 кнопка по-прежнему не активна.

![default](https://user-images.githubusercontent.com/10551765/31675342-038ad01a-b36d-11e7-8877-74e7ca5d6231.png)

**Comment by Alleshka** [comment]
Чекни теперь, в ee78b3d. Проблема наблюдалась, если открывать проект, а не создавать. Сейчас, должно быть нормально. Если норм, закрывай.
